---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-updated-application
spec:
  replicas: 3
  selector:
    matchLabels:
      type: demo
  template:
    metadata:
      name: demo-updated-pod
      labels:
        type: demo
    spec:
      containers:
        - name: c1
          image: rajavarman/new1:latest
          ports:
            - containerPort: 8080
---
---
apiVersion: v1
kind: Service
metadata:
  name: my-application-service
spec:
  type: NodePort
  selector:
    type: demo
  ports:
  - port: 80
    targetPort: 8080
---
